### ISSUE TITLE
Create PickerUpper Subsystem and State Manager

### ISSUE THREAD

**Issue by Koltara** [Team7769/2023-Season#19]
Add the state manager for the pickerupper.

**Comment by codingwithcn** [comment]
States we need
- Open 
- Close
- Up
- Down
- Intake
- Eject

Full States include
- Shake-n-Bake ( Collecting )
- Wrong Order ( Eject game object )
- Box it ( getting the game object and getting ready to transfer )
- Pizza's Ready ( Holding it for you until ready for transfer )
- Pizza stolen ( stowed )
