### ISSUE TITLE
Basic Swerve Drive in Drivetrain Subsystem

### ISSUE THREAD

**Issue by Koltara** [Team7769/2023-Season#2]
Create the basic Swerve Drive system for the Drivetrain.

**Comment by Koltara** [comment]
@codingwithcn @BigNoah37 We have a couple things to do on this for friday. 
1. Update our drive method to use field oriented speeds instead of robot oriented.
2. Add the ability for the driver controller to hold a button/trigger down to use robot oriented, otherwise defaulting to field oriented.
3. Add a button to reset the yaw on the gyro.

Work on these without committing changes and we'll go over what you have on Friday.

**Comment by codingwithcn** [comment]
I know I was missed yesterday but I will be there friday 😁😊

**Comment by Koltara** [comment]
The current code on the robot has been pushed to the branch now so make sure to fetch and pull the changes before making these changes.
